blog_theme: light
name: Chalk
paginate: 25
url: ''
about_enabled: true
discus_identifier: chalk-1
ga_analytics: UA-28631876-6
local_fonts: false
rss_enabled: true
scrollappear_enabled: true
tag_nav_enabled: false
theme_toggle: false
social:
  dribbble: nielsenramon
  facebook: null
  flickr: null
  github: nielsenramon
  linkedin: null
  twitter: nielsenramon
  email: null
  bitcoin: null
  ethereum: null
  gitlab: null
  youtube: null
  twitch: null
  discord: null
  tumblr: null
  bitbucket: null
  docker: null
  instagram: null
  keybase: null
  medium: null
  spotify: null
  stackoverflow: null
  steam: null
assets:
  plugins:
    css:
      autoprefixer: {}
    img:
      optim: {}
  source_maps: false
  sources:
    - _assets/icons
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn
collections:
  my_tags:
    output: true
    permalink: '/tag/:slug/'
defaults:
  - scope:
      path: ''
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .travis.yml
  - bin/*
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - vendor/
  - yarn.lock
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
paginate_path: '/posts/page/:num/'
permalink: 'posts/:slug'
baseurl: ''
